#' A general processing function
#'
#' This function takes in a raw count table generated by Homer's analyze repeats and creates a dataframe of the homer annotation.
#' @param no defaults
#' @keywords cats
#' @export
#' @examples
#' processAnnoTxt()


processAnnoTxt <- function(rawPath){

  #library(qdapRegex)
  raw <- read.delim(rawPath,header=T,stringsAsFactors = F)
  anno <- raw[,c(1:8)]
  colnames(anno)[1] <- "transcript_id"
  anno$gene_name <- vapply(strsplit(raw[,8],"[|]+"), `[`, 1, FUN.VALUE=character(1))
  row.names(anno) <- anno[,1]

  return(anno)
}
