#' A general processing function
#'
#' This function takes in a raw count table generated by Homer's analyze repeats and creates a dataframe with appropriate column names and uses gene names as row names.
#' @param no defaults
#' @keywords cats
#' @export
#' @examples
#' processRawTxt()


processRawTxt <- function(rawPath){

  #library(qdapRegex)
  raw <- read.delim(rawPath,header=T,stringsAsFactors = F)
  row.names(raw) <- vapply(strsplit(raw[,8],"[|]+"), `[`, 1, FUN.VALUE=character(1))
  raw <- raw[,-c(1:8)]
  colnames(raw) <- rm_between(colnames(raw), "tags.", "_S", extract=TRUE)
  return(raw)

}
